### ISSUE TITLE
Object Property settings does not work?

### ISSUE THREAD

**Issue by gguta** [LEW21/pydbus#28]
Here is a code snippet demonstrating the problem. Setting a property with the "dict" formalism has no effect, but works if use o.f.DBus.Properties proxy. Is this intentional?

```
>>> from pydbus import SystemBus
>>> bus = SystemBus()
>>> ADAPTER = 'org.bluez.Adapter1'
>>> BLUEZ = 'org.bluez'
>>> OBJECTMANAGER = 'org.freedesktop.DBus.ObjectManager'
>>> PROP = 'org.freedesktop.DBus.Properties'
>>> bluez=bus.get(BLUEZ, "/")[OBJECTMANAGER]
>>> bluez.GetManagedObjects()
{'/org/bluez/hci0': {'org.bluez.NetworkServer1': {}, 'org.freedesktop.DBus.Introspectable': {}, 'org.freedesktop.DBus.Properties': {}, 'org.bluez.Media1': {}, 'org.bluez.Adapter1': {'Pairable': True, 'Powered': False, ...
>>> HCI0_PATH='/org/bluez/hci0'
>>> bluez.GetManagedObjects()[HCI0_PATH][ADAPTER]['Powered']
False
```

The following code has no effect:

```
>>> bluez.GetManagedObjects()[HCI0_PATH][ADAPTER]['Powered']=True
>>> bluez.GetManagedObjects()[HCI0_PATH][ADAPTER]['Powered']
False
```

This works:

```
>>> adapter_prop=bus.get(BLUEZ, HCI0_PATH)[PROP]
>>> from gi.repository import GLib
>>> variant = GLib.Variant('b', "True")
>>> variant
GLib.Variant('b', true)
>>> adapter_prop.Set(ADAPTER, "Powered", variant)
>>> adapter_prop.Get(ADAPTER, "Powered")
True
>>> bluez.GetManagedObjects()[HCI0_PATH][ADAPTER]['Powered']
True
```

**Comment by LEW21** [comment]
DBus methods return normal Python objects; modifying them will only change them locally, not remotely.

Looks like you can do this instead:

adapter = bus.get(BLUEZ, HCI0_PATH)[ADAPTER]
adapter.Powered = True

**Comment by LEW21** [comment]
I guess I should add prettier support for org.freedesktop.DBus.ObjectManager interface in the future.

**Comment by gguta** [comment]
Okay, I see, but that also not works:

```
>>> adapter.Powered
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pydbus/proxy_property.py", line 22, in __get__
    return instance["org.freedesktop.DBus.Properties"].Get(self._iface_name, self.__name__)
TypeError: 'org.bluez.Adapter1' object is not subscriptable
```

**Comment by LEW21** [comment]
This was fixed in https://github.com/LEW21/pydbus/commit/f2f11a1ec41360de00b1d66a3a4a24884b6f2308.
