### ISSUE TITLE
Method 'SignalPoll' returned type '(v)', but expected '(a{sv})'

### ISSUE THREAD

**Issue by filipe-cantarelli** [LEW21/pydbus#73]
I'm trying to get the return from SignalPoll from wpa_supplicant.

This is what I get: 
`Traceback (most recent call last):
  File "tool.py", line 14, in <module>
    interface.SignalPoll()
  File "/usr/lib/python3.6/site-packages/pydbus/proxy_method.py", line 75, in __call__
    0, timeout_to_glib(timeout), None).unpack()
GLib.Error: g-io-error-quark: Method 'SignalPoll' returned type '(v)', but expected '(a{sv})' (13)`

Is this a dup of #27 ?

**Comment by Hegz** [comment]
did you find a work around for this?

**Comment by filipe-cantarelli** [comment]
@Hegz, nope.
