### ISSUE TITLE
GLib.Error: g-spawn-exit-error-quark

### ISSUE THREAD

**Issue by dnutiu** [LEW21/pydbus#76]
I get the following error when trying to run the example/server.py on a rapsberry pi zero:

```
Traceback (most recent call last):
  File "server.py", line 41, in <module>
    bus = SessionBus()
  File "/usr/local/lib/python3.5/dist-packages/pydbus/bus.py", line 60, in SessionBus
    return bus_get(Bus.Type.SESSION)
  File "/usr/local/lib/python3.5/dist-packages/pydbus/bus.py", line 19, in bus_get
    return Gio.bus_get_sync(type, None).pydbus
GLib.Error: g-spawn-exit-error-quark: Error spawning command line 'dbus-launch --autolaunch=94777ddbc8184885909ad02782f90847 --binary-syntax --close-stderr': Child process exited with code 1 (1)
```

Do you have any idea why this may happen?

Linux pizerow 4.9.80+ #1098 Fri Mar 9 18:51:28 GMT 2018 armv6l GNU/Linux

**Comment by harmtemolder** [comment]
I got the same error (also for `SessionBus`), so pasted the exact command in my terminal. That resulted in this error message:

```
Autolaunch requested, but X11 support not compiled in.
Cannot continue.
```
